[package]
name = "actman"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["sync", "rt"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
